export { WorkspaceSidebar } from "./workspace-sidebar"
export { WorkspaceRightPanel } from "./workspace-right-panel"
export { DeliverablesList } from "./deliverables-list"
export { AgentsList } from "./agents-list"
export { WorkflowSteps } from "./workflow-steps"
export { ActivityFeed } from "@/components/activity-feed"
export { DocumentsList } from "./documents-list"
export type { DocumentItem } from "./documents-list"
export { StatusDot } from "./status-dot"
export { IconRail } from "./icon-rail"
// WorkspaceChatInput unified into @/components/chat-input (use variant="workspace")
export type { ChatAttachment, ActiveToggles } from "@/components/chat-input"
export { AgentDetailPanel } from "./agent-detail-panel"
export { DocumentViewerPanel } from "./document-viewer-panel"
